<?php

namespace ContainerYuhtKDJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VsMwIO5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vsMwIO5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vsMwIO5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'projet' => ['privates', '.errored..service_locator.vsMwIO5.App\\Entity\\Projets', NULL, 'Cannot autowire service ".service_locator.vsMwIO5": it references class "App\\Entity\\Projets" but no such service exists.'],
        ], [
            'projet' => 'App\\Entity\\Projets',
        ]);
    }
}
