<?php

namespace ContainerHrA1qhP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjetsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vsMwIO5.App\Entity\Projets' shared service.
     *
     * @return \App\Entity\Projets
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.vsMwIO5": it references class "App\\Entity\\Projets" but no such service exists.');
    }
}
